### PR TITLE
enh(build) Update NSClient++ to 0.5.2.41

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

This PR updates NSClient++ to its last stable version, `0.5.2.41`.
It brings nice enhancements and fixes over `0.5.2.35`.

While here, set default Centreon Plugins version number to a "dummy" number (`20000101`), as it is now automatically and properly set by the build process (or has to manually be modified by the developer in case of a manual build).
Looks better like this.

Thx 👍

### CODE REVIEW

**Comment by Sims24** [comment]
Hey @UrBnW 

Thanks, I just need to understand why TravisCI doesn't" see the repository at the moment. 

I will review all of these and merge as soon as possible. 

Simon

**Comment by UrBnW** [comment]
Hi @Sims24,
You need something like this in your https://travis-ci.org configuration :

image

You're even able in the repository details to enable/disable build for branches, for PRs etc...
Certainly we need to push a new commit if you connected Travis after the last commits, so that it will see it and build it.

**Comment by Sims24** [comment]
Thanks, Yep I know but people in charge here are struggling in finding the good security parameters ;) 

Hope it will be ready soon.

**Review by Sims24 — APPROVED** [review]

**Comment by UrBnW** [comment]
Good news, thanks you @Sims24 👍
You'll still need to update the `api_key.secure` option in the `.travis.yml` file, as described in #21.
And you'll be done !

**Pull request merged**
