### PR TITLE
enh(build): update plugins and fix veeam

### PR DESCRIPTION
**Pull request by thibaults-centreon**

### CODE REVIEW

**Comment by UrBnW** [comment]
Do the binaries still point to the [2 months old centreon-plugins version](https://github.com/centreon/centreon-plugins/tree/9b78f5274c44a63c6d8b70e7a98519eb08950326) we can see at the root of this repository ?

**Comment by thibaults-centreon** [comment]
It should have relied on the latest master but I think I've mistaken at some point.
Have to double check this before merging.

**Comment by UrBnW** [comment]
Thank you for your feedback @thibaults-centreon 👍

**Comment by thibaults-centreon** [comment]
64bit version built upon latest master commit
32bit version is still aligned on 20200410 though, will be updated in a next PR

**Comment by UrBnW** [comment]
Many thanks @thibaults-centreon 👍
As proposed [there](https://github.com/centreon/centreon-nsclient-build/issues/16), would be nice to have an automated workflow. Perhaps you already have this in mind :)

**Comment by UrBnW** [comment]
Finally see #21 for the automated workflow 😉

**Pull request merged**
