### PR TITLE
Travis CI build

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

As briefly discussed in #16, here's a Travis-CI configuration to automatically build the plugins.
It builds everything :
- Windows 32 bits check_logfiles plugins ;
- Windows 64 bits check_logfiles plugins ;
- Windows 32 bits Centreon Plugins ;
- Windows 64 bits Centreon Plugins ;
- Windows 32 bits NSclient++ ;
- Windows 64 bits NSclient++.

Version numbers are properly set according to the `check_logfiles ` & `centreon-plugins` submodules' version.

If build is done for the `master` branch, binaries are made available through a new GitHub release.

Here's a build log example :
https://travis-ci.org/github/UrBnW/centreon-nsclient-build/builds/729273397

And here's a release example :
https://github.com/UrBnW/centreon-nsclient-build/releases/tag/200922105857

To trigger a new build & release upon Centreon Plugins changes, you then just have to update (pull) the `centreon-plugins` submodule, and push this new version.
Same for check_logfiles plugin.
That's all :)

Of course, you'll have to enable Travis-Ci for this `centreon/centreon-nsclient-build` repository.
And to update the `api_key.secure` option in the `.travis.yml` file.

Thank you :+1:

### CODE REVIEW

**Comment by UrBnW** [comment]
I just added `Net::NTP` Perl module, which was missing for `os::windows::local::plugin`, `time` mode.

**Comment by UrBnW** [comment]
I just added `Net::NTP` Perl module, which was missing for `os::windows::local::plugin`, `time` mode.
Now it works fine :
```
>centreon_plugins.exe --version
Global Version: 20200629 (7c66939f4 84bbd3c)

>centreon_plugins.exe --plugin=os::windows::local::plugin --mode=time
OK: Time offset -0.088 second(s) | 'offset'=-0.088s;;;;
```

**Comment by UrBnW** [comment]
Now properly handle the `.xml` config files, as proposed [here](https://github.com/centreon/centreon-plugins/commit/57b64d2f8d282b530733f7c944bb6a826d001fe1) with @garnier-quentin 👍

**Comment by UrBnW** [comment]
This CI auto-build now also builds check_logfiles plugin 👍

**Comment by Sims24** [comment]
Hi @UrBnW 

Give us some time to setup a dedicated account to connect TravisCI and github and we will merge it ;) 

Thanks

**Comment by UrBnW** [comment]
Hi @Sims24, sure, very good news, many thanks for your feedback 👍

**Comment by travisci-centreon-plugins** [comment]
@UrBnW , let's do it

**Comment by UrBnW** [comment]
Excellent 👍
Feel free if you need assistance, I'm available.

**Comment by UrBnW** [comment]
Take care linking your project with Travis-CI, be sure to use the free version at https://travis-ci.org.

**Comment by UrBnW** [comment]
> @UrBnW , let's do it

Did you manage to perform the https://travis-ci.org connection ?
Thx 👍

**Pull request merged**
