### PR TITLE
fix(build) Add missing NTP Perl module

### PR DESCRIPTION
**Pull request by UrBnW**
Hi,

Let's add `Net:NTP` Perl module, which is missing at least for `os::windows::local::plugin`, `time` mode.
Works perfectly fine with.

Thank you 👍

### CODE REVIEW

**Comment by UrBnW** [comment]
Hi @Sims24, let's merge this please when U'll have some minutes ?
Many thx 👍

**Review by Sims24 — APPROVED** [review]

**Comment by garnier-quentin** [comment]
@UrBnW for net::ntp, we need to patch it like in that issue:
https://rt.cpan.org/Public/Bug/Display.html?id=59607

Could you add the patch in build process ?

**Comment by UrBnW** [comment]
Sure, let me reproduce the issue and add patch in build process accordingly 👍

**Comment by UrBnW** [comment]
So, I reproduced the issue.
I'm wondering whether or not patching `Net::NTP` is the good approach.
There are certainly other included modules which use `alarm` and which would suffer from this bug.
What about finding a global solution instead, for example making `--global-timeout` Windows compliant ?
Feel free :) Thx 👍

**Comment by garnier-quentin** [comment]
You cannot make it compliant in centreon-plugins.. So we need to patch Net::NTP.
It should be nsclient to timeout. But it seems like a bug in nsclient.

**Comment by UrBnW** [comment]
OK ! Let's write a proper patch and include it in the build process then 👍

**Comment by UrBnW** [comment]
See #27.

**Comment by UrBnW** [comment]
> It should be nsclient to timeout. But it seems like a bug in nsclient.

With following `nsclient.ini` configuration :
```
[/settings/external scripts]
timeout=10
```

And using `centreon_plugins.pl --plugin=apps::protocols::nrpe::plugin --custommode=nsclient --new-api ...` as client, I get the behaviour below.

When launching the `centreon_plugins.pl` command, we see 2 new `centreon_plugins.exe` processes appearing :



10 seconds later, the `centreon_plugins.pl` returns with the following :
`Command check_centreon_plugins didn't terminate within the timeout period 10s`
Additional `--debug` gives :
`{"command":"check_centreon_plugins","lines":[{"message":"Command check_centreon_plugins didn't terminate within the timeout period 10s","perf":{}}],"result":3}`

And on Windows side, one of the 2 processes disappears, for sure killed by NSClient++ :



Unfortunately, as you can see, the bigger one remains, and it hangs forever.
So seems like NSclient++ does its job killing the external command, perhaps there's an issue with signal handling / spreading in `centreon_plugins.exe` itself.

Even with a dummy `sleep` in the plugin's code as a really simple test case, the second process does not get killed.

**Comment by UrBnW** [comment]
See #27, which does fix the issue (`Net::NTP` now properly times-out as per my various tests).

**Pull request merged**
